apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: goshort
build:
  artifacts:
  - image: goshort/links
    context: ..
    docker:
      dockerfile: services/links/Dockerfile
  local:
    useBuildkit: true
manifests:
  rawYaml:
    - https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
    - ../k8s/*
deploy:
  kubectl:
