apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: goshort
build:
  artifacts:
  - image: goshort/links
    docker:
      dockerfile: services/links/Dockerfile
  local:
    useBuildkit: true
manifests:
  rawYaml:
    - k8s/*
deploy:
  kubectl:
