apiVersion: apps/v1
kind: Deployment
metadata:
  name: links-deployment
  labels:
    name: links
spec:
  replicas: 1
  selector:
    matchLabels:
      name: links
  template:
    metadata:
      labels:
        name: links
    spec:
      containers:
      - name: links
        image: goshort/links
        ports:
        - containerPort: 3000
        env:
        - name: LINKS_POSTGRES_USER
          value: postgres
        - name: LINKS_POSTGRES_DBNAME
          value: links
        - name: LINKS_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
        - name: LINKS_POSTGRES_HOST
          value: postgres.default.svc.cluster.local
        - name: LINKS_POSTGRES_PORT
          value: "5432"
        readinessProbe:
          httpGet:
            path: /readyz
            port: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: links-nodeport
spec:
  type: NodePort
  selector:
    name: links
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001