# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-pgdata
# spec:
#   storageClassName: standard
#   accessModes:
#     - ReadWriteOnce
#   capacity:
#     storage: 2Gi
#   hostPath:
#     path: /tmp/kind/volumes/pgdata
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc-pgdata
# spec:
#   volumeName: pv-pgdata
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  containers:
  - name: postgres
    image: postgres:latest
    ports:
    - containerPort: 5432
    # volumeMounts:
    # - name: pgdata
    #   mountPath: /var/lib/postgresql/data/pgdata
    env:
    - name: POSTGRES_DB
      value: links
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres
          key: password
    - name: PGDATA
      value: /var/lib/postgresql/data/pgdata
    resources:
      requests:
        memory: "500Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1"
  # volumes:
  # - name: pgdata
  #   persistentVolumeClaim:
  #     claimName: pvc-pgdata
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    name: postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
spec:
  type: NodePort
  selector:
    name: postgres
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30000
