name: Govulncheck

on:
  push:
    branches: main
  pull_request:
    branches: main
  schedule:
    - cron: '0 8 * * 1'

permissions:
  contents: read

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
        # TODO: should propably check that in the container in which binary is build this is error prone
           go-version-input: 1.23.6 
           go-package: ./...
